name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main  # Adjust to match your repository's default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Install Microsoft Teams Action
      uses: azure/teams-notification@v1

    - name: Send Teams Notification
      env:
        TEAMS_WEBHOOK_URL: https://kaartechit.webhook.office.com/webhookb2/a02bfaab-2aea-42e9-be2c-bcc5a3eeedfb@87a25c2a-2cb4-4c40-9cbc-5268c0ed1eeb/IncomingWebhook/08536106ce3d41ec9b24db6fb2f07759/5a47267f-69bf-432d-bcb1-6366f34b8bbf
      run: npx teams-notification -m "Test report is available: [Link to report](https://github.com/rahulrm33/jestpoc/blob/main/reports/lcov-report/myClass.js.html)"


# name: Node.js CI

# on:
#   push:
#     branches:
#       - main  # Replace 'main' with the default branch of your repository

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '14'  # Adjust the Node.js version as needed

#     - name: Install dependencies
#       run: npm install

#     - name: Run tests
#       run: npm run test

